version: '3'  # Asegúrate de tener una versión especificada

services:
  app:
    container_name: Reports
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/code
    ports:
      - 3001:3001
    networks:
      - backend-network  # Conecta a la red

networks:
  backend-network:  # Define la red
